# Torch sanity checks
> Verifying that the `TorchSolver` class is working as expected.

## Data generation

In [1]:
import sys
# sys.path.append('/home/phil/aptr')
# sys.path.append('~/aptr')
sys.path.append('/Users/phil/Columbia/aPTR')
%load_ext autoreload
%autoreload 2

In [91]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from src.torch_solver import TorchSolver
from src.database import RnaDB

from src.solve_table import solve_all, score_predictions
from src.simulation import simulate_from_ids

In [3]:
# Load a database object

db = RnaDB()

/Users/phil/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1667: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = value


In [74]:
# Get 10 complete genomes

genomes = db.db[db.db["n_contigs"] == 1]["genome"].unique()
genomes_to_use = np.random.choice(genomes, 10, replace=False)

# Simulate reads from those genomes
reads, ptrs, coverages, otus = simulate_from_ids(
    db=db.db,
    ids=genomes_to_use,
    fasta_path="/home/phil/aptr/data/seqs",
    n_samples=5,
    scale=1e4,
    shuffle=False,  # Suppress shuffling to conserve memory
    fastq=False
)


Generating sample 0 for organism 158190.3...
Generating sample 0 for organism 1538644.4...
Generating sample 0 for organism 655815.4...
Generating sample 0 for organism 713604.4...
Generating sample 0 for organism 1448139.3...
Generating sample 0 for organism 41514.7...
Generating sample 0 for organism 158822.7...
Generating sample 0 for organism 135487.3...
Generating sample 0 for organism 1042156.4...
Generating sample 0 for organism 467705.9...
Sample RNA:
[{'b7f41b025015db33fc3c70196e412905': 15, '370320f84fb907dc06dff584270a9ee5': 2}, {'c27fc07a69127cb5342a030dc64f6e78': 9, '83aa7ef534f9dd6e2f2559e2ad40b4bf': 5}, {'198bdbdc91dcecab92f812c764c142fb': 0, '2e6daf417dfd38a37f76ce679cf8366f': 1}, {'ba3405f355c4a84fa05463556ef463cb': 0, 'd29e6176bf0c86b43bc365e98acfc528': 0, '3c80218ac1294cf64d118bbc672c0595': 0}, {'f39f35965b1d20a9601584dfe085cc88': 9, '1f8c69aac679b5c6491970ab010f52e6': 1, 'b85b2777aac3f29822017387febe1f2e': 2}, {'556a8129572431ad0f63471d81f5c333': 12, 'ad1139d8d17b72

Now let's take a second to look at all of the simulation outputs:

In [76]:
print(reads) # Should be None, since we didn't ask for fastq output

None


In [77]:
print(ptrs) # A #{genomes} x #{samples} matrix of PTRs
# In this case, should be 10x5
print(ptrs.shape)

[[1.296476   1.22836694 1.69989888 1.37453742 1.28500123]
 [1.81078708 1.50818829 1.12666137 1.84335023 1.67940566]
 [1.17272828 1.32361942 1.73033557 1.28527683 1.9838819 ]
 [1.76765625 1.52760728 1.95606811 1.15563401 1.39603746]
 [1.13740399 1.81536428 1.50787392 1.95740882 1.1959742 ]
 [1.29915352 1.44219008 1.28869098 1.16721832 1.89333107]
 [1.56818202 1.90765779 1.06025922 1.62804339 1.50799788]
 [1.34288533 1.89917305 1.49072891 1.12754738 1.08295759]
 [1.07589977 1.99070998 1.69732122 1.28146579 1.54071823]
 [1.69656163 1.23173143 1.85870135 1.49720755 1.55908333]]
(10, 5)


In [78]:
print(coverages)
print(coverages.shape) # Should also be 10x5, positive integers

[[18053 12196  1756 15427 16842]
 [18605   728  3885 15899  6352]
 [ 5194 16834   976 14236 39945]
 [ 2648  8829 33764  6526  7175]
 [13334 37327 21571 16154  4521]
 [31733  3175  2411  5635 14281]
 [  982   924 16316  9404  1791]
 [ 3925  3015 30935 10028   854]
 [ 2856   611  2178 18642   279]
 [32485 31673  5689   618  8531]]
(10, 5)


In [79]:
print(otus)

                                     0     1     2     3     4
b7f41b025015db33fc3c70196e412905  15.0   5.0   0.0  11.0  11.0
370320f84fb907dc06dff584270a9ee5   2.0   4.0   0.0   1.0   3.0
c27fc07a69127cb5342a030dc64f6e78   9.0   1.0   3.0  11.0   9.0
83aa7ef534f9dd6e2f2559e2ad40b4bf   5.0   0.0   1.0   6.0   0.0
198bdbdc91dcecab92f812c764c142fb   0.0   1.0   0.0   3.0   8.0
2e6daf417dfd38a37f76ce679cf8366f   1.0   1.0   0.0   4.0   8.0
ba3405f355c4a84fa05463556ef463cb   0.0   1.0   1.0   0.0   0.0
d29e6176bf0c86b43bc365e98acfc528   0.0   1.0   1.0   2.0   1.0
3c80218ac1294cf64d118bbc672c0595   0.0   1.0   1.0   0.0   0.0
f39f35965b1d20a9601584dfe085cc88   9.0  33.0  21.0  18.0   3.0
1f8c69aac679b5c6491970ab010f52e6   1.0   4.0   3.0   1.0   0.0
b85b2777aac3f29822017387febe1f2e   2.0   2.0   4.0   4.0   0.0
556a8129572431ad0f63471d81f5c333  12.0   0.0   1.0   3.0   4.0
ad1139d8d17b7276132087bf4682045c   5.0   2.0   0.0   0.0   1.0
c6fe5d3d4af66c90ff7df941c23967f1   6.0   0.0   1.0   0.

## Torch checks

Remember, the TorchSolver object assumes you have a 'genomes' dict which has the keys:
* seqs -> indices for which sequence the genome has
* pos -> start position for RNA gene

In [80]:
solver_genomes, md5s = db.generate_genome_objects(genomes_to_use)
print(solver_genomes)
print(len(solver_genomes)) # Should be 10, since there are 10 genomes

[{'id': '158190.3', 'pos': array([0.36870599, 0.05386492, 0.05206312, 0.4038798 ]), 'seqs': [0, 0, 0, 1]}, {'id': '1538644.4', 'pos': array([0.03367286, 0.01410787, 0.03505736, 0.08001561, 0.42412868,
       0.13796746, 0.22024391, 0.19420117]), 'seqs': [2, 2, 2, 2, 3, 3, 2, 2]}, {'id': '655815.4', 'pos': array([0.3692223 , 0.60811316, 0.00403924]), 'seqs': [4, 5, 5]}, {'id': '713604.4', 'pos': array([0.12651841, 0.34689584, 0.22539473, 0.25593295]), 'seqs': [6, 7, 8, 7]}, {'id': '1448139.3', 'pos': array([0.16435212, 0.00907711, 0.02554103, 0.06524982, 0.01749113,
       0.19055063, 0.81160136, 0.07228189, 0.09243017, 0.03625559]), 'seqs': [9, 10, 9, 9, 9, 9, 9, 9, 9, 11]}, {'id': '41514.7', 'pos': array([0.07106634, 0.08936011, 0.75653234, 0.0306175 , 0.01029364,
       0.06107764, 0.2343136 ]), 'seqs': [12, 13, 12, 14, 15, 16, 17]}, {'id': '158822.7', 'pos': array([0.03045775, 0.1834427 , 0.20539586, 0.05412395, 0.05569944,
       0.07173006, 0.07988342]), 'seqs': [18, 19, 20, 21, 2

In [98]:
# Here we initialize a TorchSolver with the genomes and coverages from before

solver = TorchSolver()
solver.set_vals(
    genomes=solver_genomes,
    coverages=otus[0]
)

In [101]:
# Check that a_hat updates 

print(solver.a_hat)
solver.train()
print(solver.a_hat)

tensor([0.7543, 0.4381, 0.1231, 0.4828, 0.1528, 0.3969, 0.1638, 0.8205, 0.9877,
        0.4945], requires_grad=True)
tensor([0.7543, 0.4381, 0.1231, 0.4828, 0.1528, 0.3969, 0.1638, 0.8205, 0.9877,
        0.4945], requires_grad=True)


In [122]:
# Let's try to write out the torch model here
import torch

# Learnable parameters are a_hat and b_hat
a_hat = torch.rand(10, dtype=torch.float32)
b_hat = torch.log(1 + torch.rand(10, dtype=torch.float32)) # log-PTR

# Let's just make copies of the existing C, D, E matrices
C = torch.tensor(solver.members, dtype=torch.float32)
D = torch.tensor(solver.dists, dtype=torch.float32)
E = torch.tensor(solver.gene_to_seq, dtype=torch.float32)
f_true = torch.tensor(otus[0], dtype=torch.float32)

# Some counts from the model
n = solver.n
m = solver.m
k = solver.k

# LR hyperparameter
lr = 1e-3

for i in range(10000):
    # Forward pass
    g = a_hat @ C + 1 - b_hat @ D
    f = torch.exp(g) @ E

    # Loss
    loss = torch.sum((f - f_true)**2)
    print(loss)

    # Gradients
    dL_df = f - f_true
    dL_dg = (2 / k) * torch.exp(g) * (E @ dL_df)
    dL_da = C @ dL_dg
    dL_db = -D @ dL_dg

    # Update parameters
    a_hat = a_hat - lr * dL_da
    b_hat = b_hat - lr * dL_db


<ipython-input-122-a403f4a349ca>:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  C = torch.tensor(solver.members, dtype=torch.float32)
<ipython-input-122-a403f4a349ca>:10: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  D = torch.tensor(solver.dists, dtype=torch.float32)
<ipython-input-122-a403f4a349ca>:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  E = torch.tensor(solver.gene_to_seq, dtype=torch.float32)


tensor(936.7438)
tensor(885.5349)
tensor(840.9217)
tensor(801.6381)
tensor(766.7299)
tensor(735.4643)
tensor(707.2673)
tensor(681.6830)
tensor(658.3440)
tensor(636.9504)
tensor(617.2551)
tensor(599.0524)
tensor(582.1695)
tensor(566.4597)
tensor(551.7983)
tensor(538.0781)
tensor(525.2065)
tensor(513.1027)
tensor(501.6964)
tensor(490.9259)
tensor(480.7367)
tensor(471.0803)
tensor(461.9139)
tensor(453.1991)
tensor(444.9017)
tensor(436.9906)
tensor(429.4380)
tensor(422.2190)
tensor(415.3104)
tensor(408.6917)
tensor(402.3438)
tensor(396.2497)
tensor(390.3934)
tensor(384.7604)
tensor(379.3374)
tensor(374.1123)
tensor(369.0736)
tensor(364.2109)
tensor(359.5146)
tensor(354.9757)
tensor(350.5859)
tensor(346.3375)
tensor(342.2233)
tensor(338.2365)
tensor(334.3710)
tensor(330.6210)
tensor(326.9809)
tensor(323.4457)
tensor(320.0106)
tensor(316.6711)
tensor(313.4230)
tensor(310.2624)
tensor(307.1855)
tensor(304.1888)
tensor(301.2690)
tensor(298.4231)
tensor(295.6480)
tensor(292.9410)
tensor(290.299

In [134]:
# The same model, but using Adam:

# Learnable parameters are a_hat and b_hat
a_hat = torch.rand(10, dtype=torch.float32, requires_grad=True)
b_hat = torch.rand(10, dtype=torch.float32, requires_grad=True) # log-PTR
b = torch.log(1 + b_hat) # log-PTR

# Let's just make copies of the existing C, D, E matrices
C = torch.tensor(solver.members, dtype=torch.float32)
D = torch.tensor(solver.dists, dtype=torch.float32)
E = torch.tensor(solver.gene_to_seq, dtype=torch.float32)
f_true = torch.tensor(otus[0], dtype=torch.float32)

# Some counts from the model
n = solver.n
m = solver.m
k = solver.k

# LR hyperparameter
lr = 1e-3

# Optimizer
optimizer = torch.optim.Adam([a_hat, b_hat], lr=lr)

for i in range(10000):
    # Forward pass
    g = a_hat @ C + 1 - b @ D
    f = torch.exp(g) @ E

    # Loss: use torch built-in
    loss = torch.nn.functional.mse_loss(f, f_true)
    print(loss)

    # Update parameters
    optimizer.zero_grad()
    loss.backward(retain_graph=True)
    optimizer.step()

<ipython-input-134-e44ddbffe4fe>:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  C = torch.tensor(solver.members, dtype=torch.float32)
<ipython-input-134-e44ddbffe4fe>:10: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  D = torch.tensor(solver.dists, dtype=torch.float32)
<ipython-input-134-e44ddbffe4fe>:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  E = torch.tensor(solver.gene_to_seq, dtype=torch.float32)


tensor(61.4593, grad_fn=<MseLossBackward0>)
tensor(61.3214, grad_fn=<MseLossBackward0>)
tensor(61.1838, grad_fn=<MseLossBackward0>)
tensor(61.0465, grad_fn=<MseLossBackward0>)
tensor(60.9094, grad_fn=<MseLossBackward0>)
tensor(60.7727, grad_fn=<MseLossBackward0>)
tensor(60.6363, grad_fn=<MseLossBackward0>)
tensor(60.5002, grad_fn=<MseLossBackward0>)
tensor(60.3645, grad_fn=<MseLossBackward0>)
tensor(60.2290, grad_fn=<MseLossBackward0>)
tensor(60.0939, grad_fn=<MseLossBackward0>)
tensor(59.9591, grad_fn=<MseLossBackward0>)
tensor(59.8246, grad_fn=<MseLossBackward0>)
tensor(59.6905, grad_fn=<MseLossBackward0>)
tensor(59.5567, grad_fn=<MseLossBackward0>)
tensor(59.4232, grad_fn=<MseLossBackward0>)
tensor(59.2901, grad_fn=<MseLossBackward0>)
tensor(59.1574, grad_fn=<MseLossBackward0>)
tensor(59.0250, grad_fn=<MseLossBackward0>)
tensor(58.8929, grad_fn=<MseLossBackward0>)
tensor(58.7612, grad_fn=<MseLossBackward0>)
tensor(58.6298, grad_fn=<MseLossBackward0>)
tensor(58.4988, grad_fn=<MseLoss

In [135]:
# The same model, but using epochs:

# Global parameters
N_EPOCHS = 1000
LR = 1e-3
ITERATIONS_PER_EPOCH = 1000

# Learnable parameters are a_hat and b_hat
a_hat = torch.rand(10, dtype=torch.float32, requires_grad=True)
b_hat = torch.rand(10, dtype=torch.float32, requires_grad=True) # log-PTR
b = torch.log(1 + b_hat) # log-PTR

# Let's just make copies of the existing C, D, E matrices
C = torch.tensor(solver.members, dtype=torch.float32)
D = torch.tensor(solver.dists, dtype=torch.float32)
E = torch.tensor(solver.gene_to_seq, dtype=torch.float32)
f_true = torch.tensor(otus[0], dtype=torch.float32)

# Some counts from the model
n = solver.n
m = solver.m
k = solver.k

# LR hyperparameter
lr = 1e-3

# Optimizer
optimizer = torch.optim.Adam([a_hat, b_hat], lr=lr)

for epoch in range(N_EPOCHS):
    for iter in range(ITERATIONS_PER_EPOCH):
        # Forward pass
        g = a_hat @ C + 1 - b @ D
        f = torch.exp(g) @ E

        # Loss: use torch built-in
        loss = torch.nn.functional.mse_loss(f, f_true)

        # Update parameters
        optimizer.zero_grad()
        loss.backward(retain_graph=True)
        optimizer.step()
    print(loss)

<ipython-input-135-b9563d2e2046>:14: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  C = torch.tensor(solver.members, dtype=torch.float32)
<ipython-input-135-b9563d2e2046>:15: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  D = torch.tensor(solver.dists, dtype=torch.float32)
<ipython-input-135-b9563d2e2046>:16: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  E = torch.tensor(solver.gene_to_seq, dtype=torch.float32)


tensor(16.8951, grad_fn=<MseLossBackward0>)
tensor(6.8213, grad_fn=<MseLossBackward0>)
tensor(3.9371, grad_fn=<MseLossBackward0>)
tensor(2.9131, grad_fn=<MseLossBackward0>)
tensor(2.5270, grad_fn=<MseLossBackward0>)
tensor(2.3799, grad_fn=<MseLossBackward0>)
tensor(2.3191, grad_fn=<MseLossBackward0>)
tensor(2.2894, grad_fn=<MseLossBackward0>)
tensor(2.2735, grad_fn=<MseLossBackward0>)
tensor(2.2651, grad_fn=<MseLossBackward0>)
tensor(2.2607, grad_fn=<MseLossBackward0>)
tensor(2.2585, grad_fn=<MseLossBackward0>)
tensor(2.2575, grad_fn=<MseLossBackward0>)
tensor(2.2570, grad_fn=<MseLossBackward0>)
tensor(2.2567, grad_fn=<MseLossBackward0>)
tensor(2.2566, grad_fn=<MseLossBackward0>)
tensor(2.2565, grad_fn=<MseLossBackward0>)
tensor(2.2565, grad_fn=<MseLossBackward0>)
tensor(2.2564, grad_fn=<MseLossBackward0>)
tensor(2.2564, grad_fn=<MseLossBackward0>)
tensor(2.2564, grad_fn=<MseLossBackward0>)
tensor(2.2564, grad_fn=<MseLossBackward0>)
tensor(2.2564, grad_fn=<MseLossBackward0>)
tensor(2.2

KeyboardInterrupt: 

In [160]:
solver = TorchSolver(genomes=solver_genomes, coverages=otus[0])

optimizer = torch.optim.Adam([solver.a_hat, solver.b_hat], lr=1e-4)

for epoch in range(N_EPOCHS):
    for iter in range(ITERATIONS_PER_EPOCH):
        # Forward pass
        f = solver()

        # Loss: use torch built-in
        loss = torch.nn.functional.mse_loss(f, f_true)

        # Update parameters
        optimizer.zero_grad()
        loss.backward(retain_graph=True)
        optimizer.step()
    print(loss)

tensor(54.2684, grad_fn=<MseLossBackward0>)
tensor(42.5340, grad_fn=<MseLossBackward0>)
tensor(33.7842, grad_fn=<MseLossBackward0>)
tensor(26.9954, grad_fn=<MseLossBackward0>)
tensor(21.6117, grad_fn=<MseLossBackward0>)
tensor(17.3093, grad_fn=<MseLossBackward0>)
tensor(13.8624, grad_fn=<MseLossBackward0>)
tensor(11.1064, grad_fn=<MseLossBackward0>)
tensor(8.9153, grad_fn=<MseLossBackward0>)
tensor(7.1880, grad_fn=<MseLossBackward0>)
tensor(5.8355, grad_fn=<MseLossBackward0>)
tensor(4.7770, grad_fn=<MseLossBackward0>)
tensor(3.9486, grad_fn=<MseLossBackward0>)
tensor(3.3029, grad_fn=<MseLossBackward0>)
tensor(2.8035, grad_fn=<MseLossBackward0>)
tensor(2.4214, grad_fn=<MseLossBackward0>)
tensor(2.1331, grad_fn=<MseLossBackward0>)
tensor(1.9189, grad_fn=<MseLossBackward0>)
tensor(1.7620, grad_fn=<MseLossBackward0>)
tensor(1.6478, grad_fn=<MseLossBackward0>)
tensor(1.5633, grad_fn=<MseLossBackward0>)
tensor(1.4974, grad_fn=<MseLossBackward0>)
tensor(1.4418, grad_fn=<MseLossBackward0>)
ten

In [157]:
solver.b_hat.shape

torch.Size([54])

In [102]:
solver.members

tensor([[1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
         1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0.,