# Testing matrix-based generator
> As we move from a vector- to a matrix-based generator, does anything go wrong?

In [1]:
import sys
sys.path.append('/home/phil/aptr')
%load_ext autoreload
%autoreload 2

In [4]:
from src.simulation_new import (
    _exact_coverage_curve,
    _exact_coverage_curve_genome,
    _coverage_16s_and_wgs,
    _sample_from_system,
    simulate_samples
)
from src.database import RnaDB

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [7]:
_exact_coverage_curve([.5, .1], 1)

array([1.64872127, 2.45960311])

In [8]:
_exact_coverage_curve(log_ptr=1, distances=np.random.rand(5, 5))

array([[1.54067137, 2.63453437, 2.6548019 , 1.11457739, 1.08356963],
       [1.84897624, 1.33789147, 1.92609274, 2.39828905, 1.17126971],
       [1.68229   , 2.68276867, 2.37080193, 2.22281724, 2.02313307],
       [1.79953079, 2.66682448, 2.05847836, 1.29110997, 2.09588982],
       [2.12449731, 1.15665318, 2.39797984, 2.37058182, 1.06443937]])

In [10]:
from src.oor_distance import oor_distance

In [81]:
dists = oor_distance(np.random.rand(5, 5), 0.5, 1)

_exact_coverage_curve([.5, .1, 1, .5, 3], distances=dists)

array([[2.5451908 , 2.59682492, 1.69257189, 2.29211991, 2.01813074],
       [2.29238499, 2.57903785, 2.462902  , 2.47493138, 1.25755837],
       [2.4102828 , 2.58615763, 1.41133992, 1.88718947, 0.87777608],
       [1.85148466, 2.53182616, 2.0622297 , 2.27537933, 0.71874446],
       [1.83148055, 2.55122252, 1.24373266, 2.01744099, 0.41285554]])

In [95]:
_exact_coverage_curve([.5, .1, 1, .5, 3], oor=0.5, locations=np.random.rand(10,5), size=1+np.random.rand(10))

(10, 5)
(10,)
[False False False False False False False False False False]
False


array([[2.24160682, 2.69249856, 2.34756136, 2.21161802, 1.80402572],
       [2.57552275, 2.66478522, 2.57366581, 2.18053669, 0.57109752],
       [2.51628558, 2.66770691, 2.37626655, 2.10375809, 1.79372772],
       [2.20949331, 2.61974531, 1.37056809, 2.68261146, 1.88708098],
       [2.3715213 , 2.60284994, 2.08407469, 2.56926474, 1.1175717 ],
       [2.0125428 , 2.67742993, 2.00024518, 2.59319727, 1.04261553],
       [2.03778756, 2.66082275, 2.25210529, 2.10132633, 0.58016685],
       [2.48908209, 2.51478618, 1.80682223, 1.98358056, 1.44748838],
       [2.30482916, 2.56901027, 1.80726414, 2.55084758, 1.95131643],
       [2.52818829, 2.65086439, 1.46521804, 2.11286327, 0.9492771 ]])

In [86]:
np.max(np.random.rand(10, 5)) > 1+np.random.rand(10)

array([False, False, False, False, False, False, False, False, False,
       False])

In [89]:
(0.5 > 1+np.random.rand(10)).any()

False

In [100]:
np.arange(10)[:, None][::-1]

array([[9],
       [8],
       [7],
       [6],
       [5],
       [4],
       [3],
       [2],
       [1],
       [0]])

In [119]:
x = np.arange(0, 1.01, 1/100)

In [120]:
oor_distance(x[:50], oor=0.5, size=1)

array([[1.  , 0.98, 0.96, 0.94, 0.92, 0.9 , 0.88, 0.86, 0.84, 0.82, 0.8 ,
        0.78, 0.76, 0.74, 0.72, 0.7 , 0.68, 0.66, 0.64, 0.62, 0.6 , 0.58,
        0.56, 0.54, 0.52, 0.5 , 0.48, 0.46, 0.44, 0.42, 0.4 , 0.38, 0.36,
        0.34, 0.32, 0.3 , 0.28, 0.26, 0.24, 0.22, 0.2 , 0.18, 0.16, 0.14,
        0.12, 0.1 , 0.08, 0.06, 0.04, 0.02]])

In [122]:
    x = np.arange(0, 1.01, 0.01)
    print(oor_distance(x[:50], 0, 1))
    print(oor_distance(x[51:], 0, 1)[::-1])


[[0.   0.02 0.04 0.06 0.08 0.1  0.12 0.14 0.16 0.18 0.2  0.22 0.24 0.26
  0.28 0.3  0.32 0.34 0.36 0.38 0.4  0.42 0.44 0.46 0.48 0.5  0.52 0.54
  0.56 0.58 0.6  0.62 0.64 0.66 0.68 0.7  0.72 0.74 0.76 0.78 0.8  0.82
  0.84 0.86 0.88 0.9  0.92 0.94 0.96 0.98]]
[[1.02 1.04 1.06 1.08 1.1  1.12 1.14 1.16 1.18 1.2  1.22 1.24 1.26 1.28
  1.3  1.32 1.34 1.36 1.38 1.4  1.42 1.44 1.46 1.48 1.5  1.52 1.54 1.56
  1.58 1.6  1.62 1.64 1.66 1.68 1.7  1.72 1.74 1.76 1.78 1.8  1.82 1.84
  1.86 1.88 1.9  1.92 1.94 1.96 1.98 2.  ]]


In [124]:
oor_distance(x[51:], 0, 1)

array([[1.02, 1.04, 1.06, 1.08, 1.1 , 1.12, 1.14, 1.16, 1.18, 1.2 , 1.22,
        1.24, 1.26, 1.28, 1.3 , 1.32, 1.34, 1.36, 1.38, 1.4 , 1.42, 1.44,
        1.46, 1.48, 1.5 , 1.52, 1.54, 1.56, 1.58, 1.6 , 1.62, 1.64, 1.66,
        1.68, 1.7 , 1.72, 1.74, 1.76, 1.78, 1.8 , 1.82, 1.84, 1.86, 1.88,
        1.9 , 1.92, 1.94, 1.96, 1.98, 2.  ]])

In [130]:
2 * x[51:] - np.array(1).flatten()[:, None] - np.array(0).flatten()[:, None]

array([[0.02, 0.04, 0.06, 0.08, 0.1 , 0.12, 0.14, 0.16, 0.18, 0.2 , 0.22,
        0.24, 0.26, 0.28, 0.3 , 0.32, 0.34, 0.36, 0.38, 0.4 , 0.42, 0.44,
        0.46, 0.48, 0.5 , 0.52, 0.54, 0.56, 0.58, 0.6 , 0.62, 0.64, 0.66,
        0.68, 0.7 , 0.72, 0.74, 0.76, 0.78, 0.8 , 0.82, 0.84, 0.86, 0.88,
        0.9 , 0.92, 0.94, 0.96, 0.98, 1.  ]])

In [131]:
oor_distance(x[51:], 0, 1)

array([[1.02, 1.04, 1.06, 1.08, 1.1 , 1.12, 1.14, 1.16, 1.18, 1.2 , 1.22,
        1.24, 1.26, 1.28, 1.3 , 1.32, 1.34, 1.36, 1.38, 1.4 , 1.42, 1.44,
        1.46, 1.48, 1.5 , 1.52, 1.54, 1.56, 1.58, 1.6 , 1.62, 1.64, 1.66,
        1.68, 1.7 , 1.72, 1.74, 1.76, 1.78, 1.8 , 1.82, 1.84, 1.86, 1.88,
        1.9 , 1.92, 1.94, 1.96, 1.98, 2.  ]])

In [147]:
d1 = 2 * x[51:] - np.array(0).flatten()[:,None]
d1

array([[1.02, 1.04, 1.06, 1.08, 1.1 , 1.12, 1.14, 1.16, 1.18, 1.2 , 1.22,
        1.24, 1.26, 1.28, 1.3 , 1.32, 1.34, 1.36, 1.38, 1.4 , 1.42, 1.44,
        1.46, 1.48, 1.5 , 1.52, 1.54, 1.56, 1.58, 1.6 , 1.62, 1.64, 1.66,
        1.68, 1.7 , 1.72, 1.74, 1.76, 1.78, 1.8 , 1.82, 1.84, 1.86, 1.88,
        1.9 , 1.92, 1.94, 1.96, 1.98, 2.  ]])

In [136]:
d2 = 2 * np.abs(x[51:] - np.array(1).flatten()[:, None])
d2

array([[0.98, 0.96, 0.94, 0.92, 0.9 , 0.88, 0.86, 0.84, 0.82, 0.8 , 0.78,
        0.76, 0.74, 0.72, 0.7 , 0.68, 0.66, 0.64, 0.62, 0.6 , 0.58, 0.56,
        0.54, 0.52, 0.5 , 0.48, 0.46, 0.44, 0.42, 0.4 , 0.38, 0.36, 0.34,
        0.32, 0.3 , 0.28, 0.26, 0.24, 0.22, 0.2 , 0.18, 0.16, 0.14, 0.12,
        0.1 , 0.08, 0.06, 0.04, 0.02, 0.  ]])

In [145]:
d3 = 2 * np.abs(x[51:] - np.array(1).flatten()[:, None])
d3

array([[0.98, 0.96, 0.94, 0.92, 0.9 , 0.88, 0.86, 0.84, 0.82, 0.8 , 0.78,
        0.76, 0.74, 0.72, 0.7 , 0.68, 0.66, 0.64, 0.62, 0.6 , 0.58, 0.56,
        0.54, 0.52, 0.5 , 0.48, 0.46, 0.44, 0.42, 0.4 , 0.38, 0.36, 0.34,
        0.32, 0.3 , 0.28, 0.26, 0.24, 0.22, 0.2 , 0.18, 0.16, 0.14, 0.12,
        0.1 , 0.08, 0.06, 0.04, 0.02, 0.  ]])

In [151]:
np.minimum(d1, d2, d3)

array([[0.98, 0.96, 0.94, 0.92, 0.9 , 0.88, 0.86, 0.84, 0.82, 0.8 , 0.78,
        0.76, 0.74, 0.72, 0.7 , 0.68, 0.66, 0.64, 0.62, 0.6 , 0.58, 0.56,
        0.54, 0.52, 0.5 , 0.48, 0.46, 0.44, 0.42, 0.4 , 0.38, 0.36, 0.34,
        0.32, 0.3 , 0.28, 0.26, 0.24, 0.22, 0.2 , 0.18, 0.16, 0.14, 0.12,
        0.1 , 0.08, 0.06, 0.04, 0.02, 0.  ]])

In [148]:
d1.shape

(1, 50)

In [181]:
p, o, s, d1, d2, d = oor_distance(x, oor=0, size=1)
d

ValueError: not enough values to unpack (expected 6, got 1)

In [175]:
def circular_distance(x, y, size):
    """Distance on a circle of size `size`."""
    return np.minimum(
        2 * np.abs(x - y),
        2 * (size - np.abs(x - y))
    )

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
        0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
        0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
        0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
        0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
        0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
        0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
        0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
        0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
        0.99, 1.  ]])

In [176]:
d2

array([[1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09, 1.1 ,
        1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.2 , 1.21,
        1.22, 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.3 , 1.31, 1.32,
        1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.4 , 1.41, 1.42, 1.43,
        1.44, 1.45, 1.46, 1.47, 1.48, 1.49, 1.5 , 1.51, 1.52, 1.53, 1.54,
        1.55, 1.56, 1.57, 1.58, 1.59, 1.6 , 1.61, 1.62, 1.63, 1.64, 1.65,
        1.66, 1.67, 1.68, 1.69, 1.7 , 1.71, 1.72, 1.73, 1.74, 1.75, 1.76,
        1.77, 1.78, 1.79, 1.8 , 1.81, 1.82, 1.83, 1.84, 1.85, 1.86, 1.87,
        1.88, 1.89, 1.9 , 1.91, 1.92, 1.93, 1.94, 1.95, 1.96, 1.97, 1.98,
        1.99, 2.  ]])

In [177]:
d3

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
        0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
        0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
        0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
        0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
        0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
        0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
        0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
        0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
        0.99, 1.  ]])

In [157]:
d3

array([[0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61,
        0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72,
        0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83,
        0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94,
        0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [167]:
np.abs(p - s - o)

array([0.49, 0.48, 0.47, 0.46, 0.45, 0.44, 0.43, 0.42, 0.41, 0.4 , 0.39,
       0.38, 0.37, 0.36, 0.35, 0.34, 0.33, 0.32, 0.31, 0.3 , 0.29, 0.28,
       0.27, 0.26, 0.25, 0.24, 0.23, 0.22, 0.21, 0.2 , 0.19, 0.18, 0.17,
       0.16, 0.15, 0.14, 0.13, 0.12, 0.11, 0.1 , 0.09, 0.08, 0.07, 0.06,
       0.05, 0.04, 0.03, 0.02, 0.01, 0.  ])

In [162]:
size

array([1])

In [191]:
from src.database import RnaDB

rnadb = RnaDB(
    path_to_dnaA="../../data/allDnaA.tsv",
    path_to_16s="../../data/allSSU.tsv"
)
_exact_coverage_curve_genome("903510.3", np.log(1.7), db=rnadb)

(array([0.1033291 , 0.05903599, 0.21586614, 0.01197195, 0.07877703,
        0.16483294, 0.66608203]),
 array([[2.62183232],
        [2.68886781],
        [2.32668095],
        [2.55786571],
        [2.69104469],
        [2.45616717],
        [1.77197593]]))

In [206]:
rna_indices, read_starts = _sample_from_system(
    genome="903510.3",
    log_ptr=[1.7, 1.5, 1.3],
    db=rnadb,
)
rna_indices

array([ 508008,  290245, 1061286,   58858,  387300,  810386, 3274731])

In [201]:
rna_hits = np.zeros(shape=(len(rna_indices), 3))

(7,)

(4916408, 3)

In [6]:
db = RnaDB(
    path_to_dnaA="../../data/allDnaA.tsv",
    path_to_16s="../../data/allSSU.tsv"
)

In [17]:
g2s = db.generate_genome_objects(db.complete_genomes[:3])[2]

In [18]:
g2s

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])